org: cldsolgrp09
app: tla-manager-serverless
service: tla-manager-serverless
provider:
  name: aws
  region: us-east-1
  runtime: dotnet8
  timeout: 10
  environment:
    TLA_TABLE_NAME: tla-manager-table-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - !GetAtt TLADynamoDBTable.Arn
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - "arn:aws:events:*"

package:
  artifact: bin/release/net8.0/deploy-package.zip

resources:
  Resources:
    TLADynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "name"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "name"
            KeyType: "HASH"
        TableName: ${self:provider.environment.TLA_TABLE_NAME}

functions:
  read_all_tla_groups:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.GetAllTlaGroupsFunction::GetAllTlaGroupsAsync
    events:
      - httpApi:
          path: /tlas
          method: get
  read_all_tlas:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.GetAllTlasFunction::GetAllTlasAsync
    events:
      - httpApi:
          path: /tlas/all/{name}
          method: get
  read_tla_group_by_name:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.GetTlaGroupByNameFunction::GetTlaGroupByNameAsync
    events:
      - httpApi:
          path: /tlas/{groupName}
          method: get
  add_new_tla_group:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AddTlaGroupFunction::AddTlaGroupAsync
    events:
      - httpApi:
          path: /tlas
          method: post
  add_new_tla:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AddTlaFunction::AddTlaAsync
    events:
      - httpApi:
          path: /tlas/{groupName}
          method: post
  accept_tla:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.WebApi.Functions.AcceptTlaFunction::AcceptTlaAsync
    events:
      - httpApi:
          path: /tlas/{groupName}/{name}/accept
          method: put
  seed_database:
    handler: TLAManager.Infrastructure::TLAManager.Infrastructure.Migration.DatabaseSeedHandler::SeedAsync
  