name: Deploy (manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        id: cache-target
        with:
          path: target
          key: tla-sample-app-serverless-target-latest
      - run: pwd
      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: .
          depth: 2
      - run: npm install -g serverless
      - run: serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
