name: Build and deploy main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Graphviz
        run: sudo apt-get -y install graphviz
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/cache@v4
        id: target-cache
        with:
          path: ./target/*
          key: ${{ github.sha }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/cache@v4
        id: target-cache
        with:
          path: ./target/*
          key: ${{ github.sha }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g serverless
      - name: serverless deploy
        uses: serverless/github-action@v4.0.0
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
